CardGames/skat/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView


urlpatterns = [
    url(r'^skatabend/', include('skatabend.urls', namespace="skatabend")),
    url(r'^doppelkopf/', include('doppelkopf.urls', namespace="doppelkopf")),
    url(r'^admin/', admin.site.urls),
    url(r'^', TemplateView.as_view(template_name='index.html'),
        name='home'),

]

CardGames/skatabend/urls.py
from django.conf.urls import url, include
from skatabend import views
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register(r'tournaments', views.TournamentViewSet)
router.register(r'rounds', views.RoundViewSet)
router.register(r'points', views.PointsViewSet)


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^history/$', views.history, name='history'),
    url(r'^tournament/$', views.tournament, name='tournament'),
    url(r'^tournament/(?P<tournament_id>[0-9]+)/$', views.show_tournament, name='tournamentdetail'),
    url(r'^index/$', views.insertRound, name='insertRound'),
    url(r'^(?P<round_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<round_id>[0-9]+)/calculate/$', views.calculate, name='calculate'),
    url(r'^(?P<round_id>[0-9]+)/recalculate/$', views.recalculate, name='recalculate'),
    url(r'^api/', include(router.urls)),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='skatabend'))
]

CardGames/skatabend/models.py
from django.db import models
from django.utils import timezone
from operator import itemgetter


class Tournament(models.Model):
    name = models.CharField(max_length=100)
    played_games = models.PositiveSmallIntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_round_points(self, rounds):
        points = {}
        points_player = {}
        for r in rounds:
            points.setdefault(r.player_A, []).append(r.points_A)
            points.setdefault(r.player_B, []).append(r.points_B)
            points.setdefault(r.player_C, []).append(r.points_C)
        for i, p in enumerate(points):
            points_sum = 0
            a = points[p]
            for x in a:
                points_sum += x
            points_player[p] = points_sum
        points_player_sorted = sorted(points_player.items(), key=itemgetter(1), reverse=True)
        return points_player_sorted


class Round(models.Model):
    name = models.CharField(max_length=100)
    player_A = models.CharField(max_length=100)
    player_B = models.CharField(max_length=100)
    player_C = models.CharField(max_length=100)
    points_A = models.PositiveSmallIntegerField(default=0)
    points_B = models.PositiveSmallIntegerField(default=0)
    points_C = models.PositiveSmallIntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)
    last_played = models.DateTimeField(auto_now=True)
    tournament_played = models.ForeignKey(Tournament, related_name="rounds", on_delete=models.CASCADE, default=0)

    class Meta:
        ordering = ['last_played']


    def __str__(self):
        return self.name

    def add_points(self, points):
        self.points_A += int(points.round_points_A)
        self.points_B += int(points.round_points_B)
        self.points_C += int(points.round_points_C)
        return self.save()

    def add_points_single(self, points_A, points_B, points_C):
        self.points_A += int(points_A)
        self.points_B += int(points_B)
        self.points_C += int(points_C)
        return self.save()

    def recalculate_points(self):
        self.points_A = 0
        self.points_B = 0
        self.points_C = 0
        self.save()
        points = Points.objects.filter(round=self)
        for p in points:
            self.points_A += p.round_points_A
            self.points_B += p.round_points_B
            self.points_C += p.round_points_C
        return self.save()

class Points(models.Model): # TODO: Add fields for jacks, game value and so on
    round = models.ForeignKey(Round, related_name="points", on_delete=models.CASCADE)
    round_points_A = models.PositiveSmallIntegerField(default=0)
    round_points_B = models.PositiveSmallIntegerField(default=0)
    round_points_C = models.PositiveSmallIntegerField(default=0)
    play_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}@{}'.format(self.round, self.play_date)

CardGames/skatabend/views.py
from rest_framework import viewsets
from rest_framework.decorators import detail_route
from rest_framework.response import Response
from rest_framework.reverse import reverse
from skatabend.models import Tournament, Round, Points
from skatabend.serializers import TournamentSerializer, RoundSerializer, PointsSerializer
from rest_framework.decorators import api_view


from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

def index(request):
    tournaments = Tournament.objects.order_by('pub_date')
    context = {'tournaments': tournaments}
    return render(request, 'skatabend/index.html', context)

def detail(request, round_id):
    round_now = get_object_or_404(Round, pk=round_id)
    points_id = Points.objects.filter(round=round_now)
    context = {'round_id': round_now, 'points_id': points_id}
    return render(request, 'skatabend/detail.html', context)

def history(request):
    latest_round_list = Round.objects.order_by('-pub_date')
    tournaments = Tournament.objects.order_by('-pub_date')
    context = {'latest_round_list': latest_round_list, 'tournaments': tournaments}
    return render(request, 'skatabend/history.html', context)

def tournament(request):
    tournaments = Tournament.objects.order_by('-pub_date')
    context = {'tournaments': tournaments}
    return render(request, 'skatabend/tournament.html', context)

def show_tournament(request, tournament_id):
    tournament_now = get_object_or_404(Tournament, pk=tournament_id)
    rounds = Round.objects.filter(tournament_played=tournament_now.id)
    points = tournament_now.get_round_points(rounds)
    context = {'tournament_now': tournament_now, 'rounds': rounds, 'points': points}
    return render(request, 'skatabend/tournamentdetail.html', context)

def calculate(request, round_id):
    round_now = get_object_or_404(Round, pk=round_id)
    points_id = Points(round=round_now, round_points_A=request.POST['PunkteA'], round_points_B=request.POST['PunkteB'],
                       round_points_C=request.POST['PunkteC'])
    points_id.save()
    round_now.add_points(points_id)
    return HttpResponseRedirect(reverse('skatabend:detail', args=(round_now.id,)))

def recalculate(request, round_id):
    round_now = get_object_or_404(Round, pk=round_id)
    round_now.recalculate_points()
    return HttpResponseRedirect(reverse('skatabend:detail', args=(round_now.id,)))

def insertRound(request):
    tournament = get_object_or_404(Tournament, name= request.POST['tournament'])
    round_now = Round(name=request.POST['name_round'], player_A=request.POST['player_A'], player_B=request.POST['player_B'],
                      player_C=request.POST['player_C'], tournament_played=tournament)
    round_now.save()
    return HttpResponseRedirect(reverse('skatabend:detail', args=(round_now.id,)))

class TournamentViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Tournament.objects.all()
    serializer_class = TournamentSerializer

class RoundViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Round.objects.all()
    serializer_class = RoundSerializer

class PointsViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Points.objects.all()
    serializer_class = PointsSerializer

@api_view(['GET'])
def api_root(request, format=None):
    return Response({
        'tournaments': reverse('skatabend:tournament-list', request=request, format=format),
        'rounds': reverse('skatabend:round-list', request=request, format=format),
        'points': reverse('skatabend:point-list', request=request, format=format)
    })

CardGames/skatabend/templates/skatabend/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ round_id.name }}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/SkatOrange.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/jquery.mobile.structure-1.4.5.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/jquery.mobile.icons-1.4.5.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/ownstyle.css' %}"/>

    <script src="{%static 'skatabend/jquery.min.js' %}"></script>
    <script src="{%static 'skatabend/jquery.mobile-1.4.5.min.js' %}"></script>
    <script src="{%static 'skatabend/berechneErgebnis.js' %}"></script>

</head>
<body>
<div data-role="page" data-url="{% url 'skatabend:detail' round_id.id %}" data-theme="a">


    <div data-role="header">
        <div data-role="navbar">
            <ul>
                <li><a href="{% url 'skatabend:index' %}" data-icon="home" data-ajax="false">Übersicht</a></li>
                <li><a href="{% url 'skatabend:history' %}" data-icon="bullets" data-ajax="false">Historie</a></li>
            </ul>
        </div><!-- /navbar -->
    </div>

    <div role="main" class="ui-content">
        {% if points_id %}
        <table border rules=groups id="ergebnis">
		<thead>
            <tr>
                <th>{{ round_id.player_A }}</th>
                <th>{{ round_id.player_B }}</th>
                <th>{{ round_id.player_C }}</th>
            </tr>
		</thead>
		<tbody>
            {% for points in points_id %}
            <tr>
                <td>{{ points.round_points_A }}</td>
                <td>{{ points.round_points_B }}</td>
                <td>{{ points.round_points_C }}</td>
            </tr>
            {% endfor %}
		</tbody>
		<tfoot>
            <tr>
                <td>{{ round_id.points_A }}</td>
                <td>{{ round_id.points_B }}</td>
                <td>{{ round_id.points_C }}</td>
            </tr>
		</tfoot>
        </table>
        {% else %}
        <p>No points are available.</p>
        {% endif %}


        <form action="{% url 'skatabend:calculate' round_id.id %}" method="post" id="eingabePunkte" data-ajax="false">
            {% csrf_token %}
            <fieldset data-role="controlgroup" data-type="horizontal" id="eingabePlayer">
                <label for="SpielerA">{{ round_id.player_A }}</label>
                <input id="SpielerA" type="radio" value="PunkteA" name="Spieler">
                <label for="SpielerB">{{ round_id.player_B }}</label>
                <input id="SpielerB" type="radio" value="PunkteB" name="Spieler">
                <label for="SpielerC">{{ round_id.player_C }}</label>
                <input id="SpielerC" type="radio" value="PunkteC" name="Spieler">
            </fieldset>
            <div id="Rechenfeld">
                Farbe
                <fieldset data-role="controlgroup" data-theme="SkatOrange" data-type="horizontal">
                    <label for="Kreuz">Kreuz</label>
                    <input id="Kreuz" type="radio" value="Kreuz" name="Grundwert" checked>
                    <label for="Pik">Pik</label>
                    <input id="Pik" type="radio" value="Pik" name="Grundwert">
                    <label for="Herz">Herz</label>
                    <input id="Herz" type="radio" value="Herz" name="Grundwert">
                    <label for="Karo">Karo</label>
                    <input id="Karo" type="radio" value="Karo" name="Grundwert">
                    <label for="Grande">Grande</label>
                    <input id="Grande" type="radio" value="Grande" name="Grundwert">
                    <label for="Null">Null</label>
                    <input id="Null" type="radio" value="Null" name="Grundwert">
                </fieldset>
                Buben
                <fieldset data-role="controlgroup" data-type="horizontal">
                    <label for="BubeKreuz">Kreuz</label>
                    <input id="BubeKreuz" type="checkbox" value="1" name="Buben">
                    <label for="BubePik">Pik</label>
                    <input id="BubePik" type="checkbox" value="1" name="Buben">
                    <label for="BubeHerz">Herz</label>
                    <input id="BubeHerz" type="checkbox" value="1" name="Buben">
                    <label for="BubeKaro">Karo</label>
                    <input id="BubeKaro" type="checkbox" value="1" name="Buben">
                </fieldset>

                <fieldset data-role="controlgroup" data-type="horizontal">
                    <label for="Hand">Hand</label>
                    <input id="Hand" type="checkbox" name="Hand">
                </fieldset>
                <fieldset data-role="controlgroup" data-type="horizontal">
                    <label for="Schneider">Schneider</label>
                    <input id="Schneider" type="checkbox" name="Schneider">
                    <label for="SchneiderAngesagt">angesagt</label>
                    <input id="SchneiderAngesagt" type="checkbox" name="Hand">
                </fieldset>
                <fieldset data-role="controlgroup" data-type="horizontal">
                    <label for="Schwarz">Schwarz</label>
                    <input id="Schwarz" type="checkbox" name="Schwarz">
                    <label for="SchwarzAngesagt">angesagt</label>
                    <input id="SchwarzAngesagt" type="checkbox" name="Hand">
                </fieldset>
                <fieldset data-role="controlgroup" data-type="horizontal">
                    <label for="Ouvert">Ouvert</label>
                    <input id="Ouvert" type="checkbox" name="Ouvert">
                </fieldset>
                <fieldset data-role="controlgroup" data-type="horizontal">
                    <label for="Gewonnen">Gewonnen</label>
                    <input id="Gewonnen" type="radio" name="Ausgang" checked>
                    <label for="Verloren">Verloren</label>
                    <input id="Verloren" type="radio" name="Ausgang">
                </fieldset>
                <fieldset data-role="controlgroup" data-type="horizontal">
                    <label for="PunkteA">{{ round_id.player_A }}</label>
                    <input id="PunkteA" type="number" value="0" name="PunkteA">
                    <label for="PunkteB">{{ round_id.player_B }}</label>
                    <input id="PunkteB" type="number" value="0" name="PunkteB">
                    <label for="PunkteC">{{ round_id.player_C }}</label>
                    <input id="PunkteC" type="number" value="0" name="PunkteC">
                </fieldset>
                <p id="AnzeigeMulti">

                </p>
            </div>


            <button type="reset" id="reset">Eingaben zurücksetzen</button>
            <button type="submit">Eingaben absenden</button>


        </form>
        <form action="{% url 'skatabend:recalculate' round_id.id %}" method="post" id="recalculate" data-ajax="false">
            {% csrf_token %}
            <button type="submit" id="recalculate_button">Gesamtpunktzahl erneut berechnen</button>
        </form>
    </div>


    <!-- Hier kommt der Footer -->
    <div data-role="footer">
        <h5>Eine Skat-App von Sebastian Thon</h5>
    </div>


</div>

</body>
</html>

CardGames/skatabend/templates/skatabend/history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/SkatOrange.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/jquery.mobile.structure-1.4.5.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/jquery.mobile.icons-1.4.5.min.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'skatabend/ownstyle.css' %}"/>

    <script src="{%static 'skatabend/jquery.min.js' %}"></script>
    <script src="{%static 'skatabend/jquery.mobile-1.4.5.min.js' %}"></script>

</head>
<body>
<div data-role="page" data-url="{% url 'skatabend:index' %}" data-theme="a">

    <div data-role="header">
        <div data-role="navbar">
            <ul>
                <li><a href="{% url 'skatabend:index' %}" data-icon="home" data-ajax="false">Übersicht</a></li>
                <li><a href="{% url 'skatabend:history' %}" data-icon="bullets" data-ajax="false">Historie</a></li>
            </ul>
        </div><!-- /navbar -->
    </div>


    <div role="main" class="ui-content">


    <div id="tournament">
    <h1>Turniere</h1>
        {% if tournaments %}
            {% for tournament in tournaments %}
            <h3><a href="{% url 'skatabend:tournamentdetail' tournament.id %}" data-ajax="false">{{ tournament.name }}</a></h3>
			<h6 class="Datum">Erstellt am {{ tournament.pub_date|date:"d. F Y" }}</h6>

            {% endfor %}
        {% else %}
        <p>Keine Turniere verfügbar.</p>
        {% endif %}
    </div>

    <div id="round">
    <h1>Runden</h1>
        {% if latest_round_list %}
            {% for round in latest_round_list %}
            <h3><a href="{% url 'skatabend:detail' round.id %}" data-ajax="false">{{ round.name }}</a></h3>
			<h6 class="Datum">Erstellt am {{ round.pub_date|date:"d. F Y" }}</h6>
            <table border rules="groups">
            <thead>
            <tr>
                <th>{{round.player_A}}</th>
                <th>{{round.player_B}}</th>
                <th>{{round.player_C}}</th>
            </tr>
            </thead>
                <tbody>
                <tr>
                    <td>{{round.points_A}}</td>
                    <td>{{round.points_B}}</td>
                    <td>{{round.points_C}}</td>
                </tr>
                </tbody>
            </table>
            {% endfor %}
        {% else %}
        <p>Keine Runden verfügbar.</p>
        {% endif %}
    </div>

    </div>
    <!-- Hier kommt der Footer -->
    <div data-role="footer">
        <h5>Eine Skat-App von Sebastian Thon</h5>
    </div>
</div>
</body>
</html>

CardGames/skatabend/templates/skatabend/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/SkatOrange.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/jquery.mobile.structure-1.4.5.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/jquery.mobile.icons-1.4.5.min.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'skatabend/ownstyle.css' %}"/>

    <script src="{%static 'skatabend/jquery.min.js' %}"></script>
    <script src="{%static 'skatabend/jquery.mobile-1.4.5.min.js' %}"></script>

</head>
<body>
<div data-role="page" data-url="{% url 'skatabend:index' %}" data-theme="a">

    <div data-role="header">
        <div data-role="navbar">
            <ul>
                <li><a href="{% url 'skatabend:index' %}" data-icon="home" data-ajax="false">Übersicht</a></li>
                <li><a href="{% url 'skatabend:history' %}" data-icon="bullets" data-ajax="false">Historie</a></li>
            </ul>
        </div><!-- /navbar -->
    </div>


    <div role="main" class="ui-content">

        <form action="{% url 'skatabend:insertRound' %}" method="post" id="insertRound" data-ajax="false">
            {% csrf_token %}
            <fieldset>
                <label for="name_round">Name der Runde</label>
                <input id="name_round" type="text" name="name_round" value="Skat am {% now 'd.m.Y' %}">
            </fieldset>
            <fieldset>
                <label for="player_A">Erster Geber</label>
                <input id="player_A" type="text" name="player_A">
                <label for="player_B">Zweiter Geber</label>
                <input id="player_B" type="text" name="player_B">
                <label for="player_C">Dritter Geber</label>
                <input id="player_C" type="text" name="player_C">
            </fieldset>
            <fieldset>
                <label for="tournament">Turnier</label>
                <select id="tournament" name="tournament">
                    {% for t in tournaments %}
                    <option value="{{ t.name }}">{{ t.name }}</option>
                    {% endfor %}
                </select>
            </fieldset>
            <button type="reset" id="reset">Eingaben zurücksetzen</button>
            <button type="submit">Eingaben absenden</button>
        </form>
    </div>
    <!-- Hier kommt der Footer -->
    <div data-role="footer">
        <h5>Eine Skat-App von Sebastian Thon</h5>
    </div>
</div>
</body>
</html>

CardGames/skatabend/templates/skatabend/tournament.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/SkatOrange.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/jquery.mobile.structure-1.4.5.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/jquery.mobile.icons-1.4.5.min.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'skatabend/ownstyle.css' %}"/>

    <script src="{%static 'skatabend/jquery.min.js' %}"></script>
    <script src="{%static 'skatabend/jquery.mobile-1.4.5.min.js' %}"></script>

</head>
<body>
<div data-role="page" data-url="{% url 'skatabend:index' %}" data-theme="a">

    <div data-role="header">
        <div data-role="navbar">
            <ul>
                <li><a href="{% url 'skatabend:index' %}" data-icon="home" data-ajax="false">Übersicht</a></li>
            </ul>
        </div><!-- /navbar -->
    </div>


    <div role="main" class="ui-content">
        {% if tournaments %}
        <ul>
            {% for tournament in tournaments %}
            <h3>{{ tournament.name }}</h3>
			<p id="Datum">Erstellt am {{ tournament.pub_date }}</p>
            <p>
                {{round.player_A}}({{round.points_A}}), {{round.player_B}}({{round.points_B}}),
                    {{round.player_C}}({{round.points_C}})
            </p>
            {% endfor %}
        </ul>
        {% else %}
        <p>No rounds are available.</p>
        {% endif %}

    </div>
    <!-- Hier kommt der Footer -->
    <div data-role="footer">
        <h5>Eine Skat-App von Sebastian Thon</h5>
    </div>
</div>
</body>
</html>

CardGames/skatabend/templates/skatabend/tournamentdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/SkatOrange.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/jquery.mobile.structure-1.4.5.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/jquery.mobile.icons-1.4.5.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'skatabend/ownstyle.css' %}"/>

    <script src="{% static 'skatabend/jquery.min.js' %}"></script>
    <script src="{% static 'skatabend/jquery.mobile-1.4.5.min.js' %}"></script>

</head>
<body>
<div data-role="page" data-url="{% url 'skatabend:index' %}" data-theme="a">

    <div data-role="header">
        <div data-role="navbar">
            <ul>
                <li><a href="{% url 'skatabend:index' %}" data-icon="home" data-ajax="false">Übersicht</a></li>
                <li><a href="{% url 'skatabend:history' %}" data-icon="bullets" data-ajax="false">Historie</a></li>
            </ul>
        </div><!-- /navbar -->
    </div>


    <div role="main" class="ui-content">
        <h1>{{ tournament_now.name }}</h1>
        {% if rounds %}
            <h3>Gespielte Runden</h3>
            <ul>
                {% for r in rounds %}
                    <li><a href="{% url 'skatabend:detail' r.id %}" data-ajax="false">{{ r.name }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if points %}
            <table border rules="groups">
                <thead>
                <tr>
                    <th>Spieler</th>
                    <th>Punkte</th>
                </tr>
                </thead>
                <tbody>
                {% for key, value in points %}
                    <tr>
                        <td>{{ key }}</td>
                        <td>{{ value }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No rounds are available.</p>
        {% endif %}
    </div>
    <!-- Hier kommt der Footer -->
    <div data-role="footer">
        <h5>Eine Skat-App von Sebastian Thon</h5>
    </div>
</div>
</body>
</html>