CardGames/doppelkopf/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^history/$', views.history, name='history'),
    url(r'^tournament/$', views.tournament, name='tournament'),
    url(r'^tournament/(?P<tournament_id>[0-9]+)/$', views.show_tournament, name='tournamentdetail'),
    url(r'^index/$', views.insert_round, name='insert_round'),
    url(r'^(?P<round_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<round_id>[0-9]+)/calculate/$', views.calculate, name='calculate'),
    url(r'^(?P<round_id>[0-9]+)/recalculate/$', views.recalculate, name='recalculate'),
]

CardGames/skat/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView


urlpatterns = [
    url(r'^skatabend/', include('skatabend.urls', namespace="skatabend")),
    url(r'^doppelkopf/', include('doppelkopf.urls', namespace="doppelkopf")),
    url(r'^admin/', admin.site.urls),
    url(r'^', TemplateView.as_view(template_name='index.html'),
        name='home'),

]

CardGames/doppelkopf/models.py
from django.db import models
from django.utils import timezone
from operator import itemgetter


class Tournament(models.Model):
    name = models.CharField(max_length=100)
    played_games = models.PositiveSmallIntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_round_points(self, rounds):
        points = {}
        points_player = {}
        for r in rounds:
            points.setdefault(r.player_A, []).append(r.points_A)
            points.setdefault(r.player_B, []).append(r.points_B)
            points.setdefault(r.player_C, []).append(r.points_C)
            points.setdefault(r.player_D, []).append(r.points_D)
        for i, p in enumerate(points):
            points_sum = 0
            a = points[p]
            for x in a:
                points_sum += x
            points_player[p] = points_sum
        points_player_sorted = sorted(points_player.items(), key=itemgetter(1), reverse=True)
        return points_player_sorted


class Round(models.Model):
    name = models.CharField(max_length=100)
    player_A = models.CharField(max_length=100)
    player_B = models.CharField(max_length=100)
    player_C = models.CharField(max_length=100)
    player_D = models.CharField(max_length=100)
    points_A = models.PositiveSmallIntegerField(default=0)
    points_B = models.PositiveSmallIntegerField(default=0)
    points_C = models.PositiveSmallIntegerField(default=0)
    points_D = models.PositiveSmallIntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)
    last_played = models.DateTimeField(auto_now=True)
    tournament_played = models.ForeignKey(Tournament, on_delete=models.CASCADE, default=0)

    def __str__(self):
        return self.name

    def add_points(self, points):
        self.points_A += int(points.round_points_A)
        self.points_B += int(points.round_points_B)
        self.points_C += int(points.round_points_C)
        self.points_D += int(points.round_points_D)
        return self.save()

    def add_points_single(self, points_A, points_B, points_C, points_D):
        self.points_A += int(points_A)
        self.points_B += int(points_B)
        self.points_C += int(points_C)
        self.points_D += int(points_D)
        return self.save()

    def recalculate_points(self):
        self.points_A = 0
        self.points_B = 0
        self.points_C = 0
        self.points_D = 0
        self.save()
        points = Points.objects.filter(round=self)
        for p in points:
            self.points_A += p.round_points_A
            self.points_B += p.round_points_B
            self.points_C += p.round_points_C
            self.points_D += p.round_points_D
        return self.save()

class Points(models.Model):
    round = models.ForeignKey(Round, on_delete=models.CASCADE)
    round_points_A = models.PositiveSmallIntegerField(default=0)
    round_points_B = models.PositiveSmallIntegerField(default=0)
    round_points_C = models.PositiveSmallIntegerField(default=0)
    round_points_D = models.PositiveSmallIntegerField(default=0)
    play_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}@{}'.format(self.round, self.play_date)

CardGames/doppelkopf/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Round, Points, Tournament

# Create your views here.


def index(request):
    tournaments = Tournament.objects.order_by('pub_date')
    context = {'tournaments': tournaments}
    return render(request, 'doppelkopf/index.html', context)


def detail(request, round_id):
    round_now = get_object_or_404(Round, pk=round_id)
    points_id = Points.objects.filter(round=round_now)
    context = {'round_id': round_now, 'points_id': points_id}
    return render(request, 'doppelkopf/detail.html', context)


def history(request):
    latest_round_list = Round.objects.order_by('-pub_date')
    tournaments = Tournament.objects.order_by('-pub_date')
    context = {'latest_round_list': latest_round_list, 'tournaments': tournaments}
    return render(request, 'doppelkopf/history.html', context)


def tournament(request):
    tournaments = Tournament.objects.order_by('-pub_date')
    context = {'tournaments': tournaments}
    return render(request, 'doppelkopf/tournament.html', context)


def show_tournament(request, tournament_id):
    tournament_now = get_object_or_404(Tournament, pk=tournament_id)
    rounds = Round.objects.filter(tournament_played=tournament_now.id)
    points = tournament_now.get_round_points(rounds)
    context = {'tournament_now': tournament_now, 'rounds': rounds, 'points': points}
    return render(request, 'doppelkopf/tournamentdetail.html', context)


def calculate(request, round_id):
    round_now = get_object_or_404(Round, pk=round_id)
    points_id = Points(round=round_now, round_points_A=request.POST['points_A'], round_points_B=request.POST['points_B'],
                       round_points_C=request.POST['points_C'], round_points_D=request.POST['points_D'])
    points_id.save()
    round_now.add_points(points_id)
    return HttpResponseRedirect(reverse('doppelkopf:detail', args=(round_now.id,)))


def recalculate(request, round_id):
    round_now = get_object_or_404(Round, pk=round_id)
    round_now.recalculate_points()
    return HttpResponseRedirect(reverse('doppelkopf:detail', args=(round_now.id,)))


def insert_round(request):
    tournament = get_object_or_404(Tournament, name=request.POST['tournament'])
    round_now = Round(name=request.POST['name_round'], player_A=request.POST['player_A'],
                      player_B=request.POST['player_B'],
                      player_C=request.POST['player_C'], player_D=request.POST['player_D'], tournament_played=tournament)
    round_now.save()
    return HttpResponseRedirect(reverse('doppelkopf:detail', args=(round_now.id,)))

CardGames/doppelkopf/templates/doppelkopf/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>
        {% block title %}Doppelkopf{% endblock %}
    </title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONT
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    {% load static %}

    <link rel="stylesheet" href="{% static 'doppelkopf/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'doppelkopf/css/skeleton.css' %}">
    <link rel="stylesheet" href="{% static 'doppelkopf/css/ownstyle.css' %}">

    <script src="{% static 'doppelkopf/javascript/jquery.min.js' %}"></script>
    <script src="{% static 'doppelkopf/javascript/calculator.js' %}"></script>
</head>
<body>
<div class="container">
    {% block top_navigation %}
        <div class="row" role="navigation" id="nav-bar">
            <div class="six columns">
                <a href="{% url 'doppelkopf:index' %}" class="u-full-width"><div>Übersicht</div></a>
            </div>
            <div class="six columns">
                <a href="{% url 'doppelkopf:history' %}" class="u-full-width"><div>Historie</div></a>
            </div>
        </div>
    {% endblock %}
    {% block header %}
        <h1>Titel der Seite</h1>
    {% endblock %}
        {% block content %}
            Hier ist der Content
        {% endblock %}
    {% block footer %}
        <div class="row">
            <div class="six columns">
                <a href="">Impressum</a>
            </div>
            <div class="six columns">
                Doppelkopf by Sebastian Thon
            </div>
        </div>
    {% endblock %}
</div>
</body>
</html>

CardGames/doppelkopf/templates/doppelkopf/detail.html
{% extends './base.html' %}

{% block title %}
    {{ round_id.name }}
{% endblock %}

{% block header %}
    <h1>{{ round_id.name }}</h1>
{% endblock %}

{% block content %}
    <div class="row">
        {% if points_id %}
            <table id="ergebnis" class="u-full-width">
                <thead>
                <tr>
                    <th>{{ round_id.player_A }}</th>
                    <th>{{ round_id.player_B }}</th>
                    <th>{{ round_id.player_C }}</th>
                    <th>{{ round_id.player_D }}</th>
                </tr>
                </thead>
                <tbody>
                {% for points in points_id %}
                    <tr>
                        <td>{{ points.round_points_A }}</td>
                        <td>{{ points.round_points_B }}</td>
                        <td>{{ points.round_points_C }}</td>
                        <td>{{ points.round_points_D }}</td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <td>{{ round_id.points_A }}</td>
                    <td>{{ round_id.points_B }}</td>
                    <td>{{ round_id.points_C }}</td>
                    <td>{{ round_id.points_D }}</td>
                </tr>
                </tfoot>
            </table>

        {% else %}
            Noch keine Punkte eingetragen.
        {% endif %}
    </div>
    <div class="row">
        <form action="{% url 'doppelkopf:recalculate' round_id.id %}" method="post" id="recalculate">
            {% csrf_token %}
            <button type="submit" id="recalculate_button">Gesamtpunktzahl erneut berechnen</button>
        </form>
    </div>
    <form action="{% url 'doppelkopf:calculate' round_id.id %}" method="post" id="calculate">
        {% csrf_token %}
        <h3>Spielart</h3>
        <div class="row">
            <div class="three columns">
                <label for="normal">Normal</label>
                <input id="normal" type="radio" value="normal" name="gametype" checked>
            </div>
            <div class="three columns">
                <label for="hochzeit">Hochzeit</label>
                <input id="hochzeit" type="radio" value="wedding" name="gametype">
            </div>
            <div class="three columns">
                <label for="solo">Solo</label>
                <input id="solo" type="radio" value="solo" name="gametype">
            </div>
        </div>
        <h3>Re-Partei</h3>
        <div class="row">
            <div class="three columns">
                <label for="player_A">{{ round_id.player_A }}</label>
                <input id="player_A" type="checkbox" value="player_A" name="player">
            </div>
            <div class="three columns">
                <label for="player_B">{{ round_id.player_B }}</label>
                <input id="player_B" type="checkbox" value="player_B" name="player">
            </div>
            <div class="three columns">
                <label for="player_C">{{ round_id.player_C }}</label>
                <input id="player_C" type="checkbox" value="player_C" name="player">
            </div>
            <div class="three columns">
                <label for="player_D">{{ round_id.player_D }}</label>
                <input id="player_D" type="checkbox" value="player_D" name="player">
            </div>
        </div>

        {% comment %}<h3>Sieger</h3>
        <div class="row">
            <div class="six columns">
                <label for="re-party">Re-Partei</label>
                <input id="re-party" type="radio" value="re-party" name="winner" checked>
            </div>
            <div class="six columns">
                <label for="contra-party">Kontra-Partei</label>
                <input id="contra-party" type="radio" value="contra-party" name="winner">
            </div>
        </div>{% endcomment %}
        <h3>Augenzahl</h3>
        <div class="row">
            <div class="six columns">
                <label for="points_re">Punkte Re-Partei</label>
                <input id="points_re" type="number" value="240" name="points">
            </div>
            <div class="six columns">
                <label for="points_contra">Punkte Kontra-Partei</label>
                <input id="points_contra" type="number" value="0" name="points">
            </div>
        </div>
        <h3>Sonderpunkte</h3>
        <div class="row">
            <div class="two columns">
                <label for="fox">Fuchs gefangen</label>
                <input id="fox" type="checkbox" value="fox">
            </div>
            <div class="two columns">
                <label for="doublehead">Doppelkopf</label>
                <input id="doublehead" type="checkbox" value="doublehead">
            </div>
            <div class="two columns">
                <label for="karl">Karlchen gefangen</label>
                <input id="karl" type="checkbox" value="karl">
            </div>
            <div class="two columns">
                <label for="said_re">Re angesagt</label>
                <input id="said_re" type="checkbox" value="said_re">
            </div>
            <div class="two columns">
                <label for="said_contra">Kontra angesagt</label>
                <input id="said_contra" type="checkbox" value="said_contra">
            </div>
        </div>
        <div class="row">
            <div class="two columns">
                <label for="extra">Extra-Punkte</label>
                <input id="extra" type="number" value="0">
            </div>
        </div>
        <h3>Punkte</h3>
        <div class="row">
            <div class="three columns">
                <label for="points_A">{{ round_id.player_A }}</label>
                <input id="points_A" type="number" value="0" name="points_A">
            </div>
            <div class="three columns">
                <label for="points_B">{{ round_id.player_B }}</label>
                <input id="points_B" type="number" value="0" name="points_B">
            </div>
            <div class="three columns">
                <label for="points_C">{{ round_id.player_C }}</label>
                <input id="points_C" type="number" value="0" name="points_C">
            </div>
            <div class="three columns">
                <label for="points_D">{{ round_id.player_D }}</label>
                <input id="points_D" type="number" value="0" name="points_D">
            </div>
        </div>
        <div class="row">
            <div class="six columns">
                <button type="reset" id="reset">Eingaben zurücksetzen</button>
            </div>
            <div class="six columns">
                <button type="submit">Eingaben absenden</button>
            </div>
        </div>
    </form>


{% endblock %}

CardGames/doppelkopf/templates/doppelkopf/history.html
{% extends './base.html' %}

{% block title %}
    Historie
{% endblock %}

{% block header %}
    <h1>Gespielte Spiele und Turniere</h1>
{% endblock %}

{% block content %}
    <h2>Turniere</h2>
    {% if tournaments %}
        {% for tournament in tournaments %}
            <h3><a href="{% url 'doppelkopf:tournamentdetail' tournament.id %}">{{ tournament.name }}</a></h3>
            <h6 class="Datum">Erstellt am {{ tournament.pub_date|date:"d. F Y" }}</h6>
        {% endfor %}
    {% else %}
        <p>Keine Turniere verfügbar.</p>
    {% endif %}
    <h2>Gespielte Runden</h2>
    {% if latest_round_list %}
        {% for round in latest_round_list %}
            <h3><a href="{% url 'doppelkopf:detail' round.id %}">{{ round.name }}</a></h3>
            <h6 class="Datum">Erstellt am {{ round.pub_date|date:"d. F Y" }}</h6>
            <table>
                <thead>
                <tr>
                    <th>{{ round.player_A }}</th>
                    <th>{{ round.player_B }}</th>
                    <th>{{ round.player_C }}</th>
                    <th>{{ round.player_D }}</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ round.points_A }}</td>
                    <td>{{ round.points_B }}</td>
                    <td>{{ round.points_C }}</td>
                    <td>{{ round.points_D }}</td>
                </tr>
                </tbody>
            </table>
        {% endfor %}
    {% else %}
        <p>Keine Runden verfügbar.</p>
    {% endif %}
{% endblock %}

CardGames/doppelkopf/templates/doppelkopf/index.html
{% extends './base.html' %}

{% block title %}
Doppelkopf
{% endblock %}

{% block header %}
<h1>Doppelkopf - Index</h1>
{% endblock %}

{% block content %}
<form action="{% url 'doppelkopf:insert_round' %}" method="post" id="insert_round">
    {% csrf_token %}
        <div class="row">
            <label for="name_round" class="u-full-width">Name</label>
            <input id="name_round" class="u-full-width" type="text" name="name_round" value="Doppelkopf am {% now 'd.m.Y' %}">
        </div>
        <div class="row">
            <div class="three columns">
                <label for="player_A">Erster Geber</label>
                <input id="player_A" type="text" name="player_A" placeholder="Horst">
            </div>
            <div class="three columns">
                <label for="player_B">Zweiter Geber</label>
                <input id="player_B" type="text" name="player_B" placeholder="Wilhelm">
            </div>
            <div class="three columns">
                <label for="player_C">Dritter Geber</label>
                <input id="player_C" type="text" name="player_C" placeholder="Friedrich">
            </div>
            <div class="three columns">
                <label for="player_D">Vierter Geber</label>
                <input id="player_D" type="text" name="player_D" placeholder="Hans">
            </div>
        </div>
        <div class="row">
            <label for="tournament">Turnier</label>
            <select id="tournament" class="u-full-width" name="tournament">
                {% for t in tournaments %}
                    <option value="{{ t.name }}">{{ t.name }}</option>
                    {% endfor %}
            </select>
        </div>
        <div class="row">
            <div class="six columns">
                <button type="reset" id="reset">Eingaben zurücksetzen</button>
            </div>
            <div class="six colums">
                <button type="submit">Eingaben absenden</button>
            </div>
        </div>
    </form>
{% endblock %}

CardGames/doppelkopf/templates/doppelkopf/tournament.html
{% extends './base.html' %}

{% block title %}
Turniere
{% endblock %}

{% block header %}
<h1>Gespielte Turniere</h1>
{% endblock %}

{% block content %}
    {% if tournaments %}
        <ul>
            {% for tournament in tournaments %}
            <h3>{{ tournament.name }}</h3>
			<p id="Datum">Erstellt am {{ tournament.pub_date }}</p>
            <p>
                {{round.player_A}}({{round.points_A}}), {{round.player_B}}({{round.points_B}}),
                    {{round.player_C}}({{round.points_C}})
            </p>
            {% endfor %}
        </ul>
        {% else %}
        <p>Keine Turniere verfügbar.</p>
        {% endif %}
{% endblock %}

CardGames/doppelkopf/templates/doppelkopf/tournamentdetail.html
{% extends './base.html' %}

{% block title %}
Historie
{% endblock %}

{% block header %}
 <h1>{{ tournament_now.name }}</h1>
{% endblock %}

{% block content %}
    {% if rounds %}
        <h3>Gespielte Runden</h3>
        <ul>
        {% for r in rounds %}
            <li><a href="{% url 'doppelkopf:detail' r.id %}">{{ r.name }}</a></li>
        {% endfor %}
        </ul>
    {% endif %}
        {% if points %}
        <table border rules="groups">
            <thead>
            <tr>
                <th>Spieler</th>
                <th>Punkte</th>
            </tr>
            </thead>
                <tbody>
                {% for key, value in points %}
                <tr>
                    <td>{{ key }}</td>
                    <td>{{ value }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
        <p>No rounds are available.</p>
        {% endif %}
{% endblock %}